[package]
name = "lianli-display"
version.workspace = true
edition.workspace = true

[dependencies]
wayland-client = "0.31"
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
libloading = "0.8.9"
anyhow = { workspace = true }
lianli-evdi = { path = "../lianli-evdi" }
lianli-shared = { path = "../lianli-shared" }
libc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
socket2 = { version = "0.6", features = ["all"] }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
